### ISSUE TITLE
Loglevel and different telegram groups

### ISSUE THREAD

**Issue by dakk** [openbitlab/srvcheck#123]
Integrate different loglevel with different telegram group destination, or same group with different Topics.

This is a proposal of what to do:

### Configuration
Add new fields to the config file with the following format:
```
infoLevelChatId=
warningLevelChatId=
errorLevelChatId=
```

chatIds remains as fallback, and if is set with levels, it receives all the uncatched messages

If we, for example, specify only `errorLevelChatIds`, chatIds receives the rest.

```python
class NotificationLevel:
    NotDeclared = 0
    Info = 1
    Warning = 2
    Error = 3
```

### Notification abstraction

`Notification.send` and `Notification.append` already have the `level` field. We need to add this field also to `Notification.sendPhoto`. This field should be propagated to `NotificationProvider` and `TelegramNotification`

`TelegramNotification` will:
- Parse the new config field
- Accept the level field
- If the level field is set, send the notification to all chatIds and to the level specific chats

### Notification creation
Update all the `Notification` calls to use the level field.

## Tasks

- [x] Add the new fields
- [x] Update methods adding the level field
- [x] Handle the level field in flush()
- [x] Handle the level field in DummyNotification
- [x] Handle the level field in TelegramNotification
- [x] Update all calls to notification creation to include a suitable level
- [x] Fix current test suite
- [x] Add test coverage for the new feature
- [x] Add parameter to install script and readme

**Comment by dakk** [comment]
## Tasks

- [ ] Add the new fields
- [ ] Update methods adding the level field
- [ ] Handle the level field in flush()
- [ ] Handle the level field in DummyNotification
- [ ] Handle the level field in TelegramNotification
- [ ] Update all calls to notification creation to include a suitable level
- [ ] Fix current test suite
- [ ] Add test coverage for the new feature
